import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Transaction } from "@/services/transactionService";

export const generateTransactionReport = (
  transactions: Transaction[],
  startDate: Date,
  endDate: Date,
  title: string = "Temple Financial Report"
) => {
  const doc = new jsPDF();
  const saffron: [number, number, number] = [255, 153, 51];
  
  // NORMALIZE DATES TO BE INCLUSIVE
  const sDate = new Date(startDate);
  sDate.setHours(0, 0, 0, 0);
  const eDate = new Date(endDate);
  eDate.setHours(23, 59, 59, 999);

  // Filter relevant transactions (Include ALL for the list, but only Approved for Summary)
  const filtered = transactions.filter(t => 
    t.timestamp >= sDate && 
    t.timestamp <= eDate
  );

  const startStr = sDate.toLocaleDateString();
  const endStr = eDate.toLocaleDateString();

  // PAGE 1: CASH IN (INCOME)
  doc.setFontSize(20);
  doc.setTextColor(saffron[0], saffron[1], saffron[2]);
  doc.text("Page 1: Income Report (Cash In)", 14, 22);
  
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`Period: ${startStr} to ${endStr}`, 14, 30);
  
  const cashIn = filtered.filter(t => t.type === "cash_in");
  const cashInTable = cashIn.map(t => [
    t.timestamp.toLocaleDateString(),
    t.category === 'donation' ? 'Donation' : 'Direct CashIn',
    t.category === 'donation' ? (t.forWhom || t.submittedByName) : '',
    t.paymentMethod === 'cash_online' ? 'Online' : (t.submittedByName || 'Manual'),
    `Rs. ${t.amount.toFixed(2)}`,
    t.status.replace(/_/g, ' ')
  ]);

  autoTable(doc, {
    startY: 40,
    head: [['Date', 'Type', 'Donated By', 'Method / Collector', 'Amount', 'Status']],
    body: cashInTable,
    headStyles: { fillColor: saffron },
    margin: { top: 40 },
    didDrawCell: (data) => {
      // Highlight non-approved rows slightly? Optional.
    }
  });

  const finalY1 = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY : 40;
  const approvedIn = cashIn.filter(t => t.status === 'approved' || t.status === 'received_confirmed');
  const totalIn = approvedIn.reduce((acc, t) => acc + (t.amount || 0), 0);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Approved Collected: Rs. ${totalIn.toFixed(2)}`, 14, finalY1 + 10);

  // PAGE 2: EXPENSES (CASH OUT)
  doc.addPage();
  doc.setFontSize(20);
  doc.setTextColor(saffron[0], saffron[1], saffron[2]);
  doc.text("Page 2: Expense Report", 14, 22);
  
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`Period: ${startStr} to ${endStr}`, 14, 30);

  const cashOut = filtered.filter(t => t.type === "cash_out");
  const cashOutTable = cashOut.map(t => [
    t.timestamp.toLocaleDateString(),
    t.submittedByName || "Member",
    t.description || "General Expense",
    `Rs. ${t.amount.toFixed(2)}`,
    t.status.replace(/_/g, ' ')
  ]);

  autoTable(doc, {
    startY: 40,
    head: [['Date', 'Spent By', 'Reason', 'Amount', 'Status']],
    body: cashOutTable,
    headStyles: { fillColor: [200, 50, 50] },
    margin: { top: 40 }
  });

  const finalY2 = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY : 40;
  const approvedOut = cashOut.filter(t => t.status === 'approved' || t.status === 'received_confirmed');
  const totalOut = approvedOut.reduce((acc, t) => acc + (t.amount || 0), 0);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Approved Spent: Rs. ${totalOut.toFixed(2)}`, 14, finalY2 + 10);

  // PAGE 3: SUMMARY
  doc.addPage();
  doc.setFontSize(24);
  doc.setTextColor(saffron[0], saffron[1], saffron[2]);
  doc.text("Financial Summary", 14, 40);
  
  doc.setLineWidth(0.5);
  doc.setDrawColor(saffron[0], saffron[1], saffron[2]);
  doc.line(14, 45, 100, 45);

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Finalized Collected:`, 14, 65);
  doc.setTextColor(34, 139, 34);
  doc.text(`Rs. ${totalIn.toFixed(2)}`, 100, 65);

  doc.setTextColor(0, 0, 0);
  doc.text(`Total Finalized Spent:`, 14, 80);
  doc.setTextColor(200, 50, 50);
  doc.text(`Rs. ${totalOut.toFixed(2)}`, 100, 80);

  doc.setDrawColor(200, 200, 200);
  doc.line(14, 90, 140, 90);

  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text(`Net Balance Left:`, 14, 105);
  doc.setTextColor(saffron[0], saffron[1], saffron[2]);
  doc.text(`Rs. ${(totalIn - totalOut).toFixed(2)}`, 100, 105);

  // Footer on summary
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Note: Summary only includes finalized (Approved / Received) transactions.", 14, 125);
  doc.text("Generated by Temple Management System", 14, 135);
  doc.text(`Date of Generation: ${new Date().toLocaleString()}`, 14, 140);

  doc.save(`Temple_Report_${startStr}_to_${endStr}.pdf`);
};
